config/routes.rb
Tuduk::Application.routes.draw do

  resources :invitations, only: [:index, :new]
  resources :authentications
  resources :comments
  resources :likes
  resources :movies, only: [:show, :index, :new]
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy, :index]
  resources :activities, only: [:index]

  root :to => 'pages#home'

  match "/signup", to: 'users#new'
  match "/signin", to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match "/about", to: 'pages#about'
  match "/submit", to: 'pages#submit'
  match "/bookmarklet", to: 'pages#bookmarklet'
  match "/library", to: 'pages#library'

  match '/auth/:provider/callback' => 'authentications#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	validates :content, presence: true
	validates :user_id, presence: true

	belongs_to :movie, :counter_cache => true
	belongs_to :user

	after_save :log_activity

	private

		def log_activity
			Activity.log_data(self, 2)
		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :signed_in_user
  before_filter :correct_user, only: [:destroy]
  
  def create
    @comment = Comment.new(params[:comment])
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

    def correct_user
      comment = Comment.find(params[:id])
      user = comment.user
      redirect_to(root_path) unless current_user?(user)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="comment_<%= comment.id %>">
	<%= link_to(image_tag(avatar_url_for(comment.user), :class => "avatar"), user_path(comment.user), :class => "avatar") %>
	<strong><%= comment.user.name %></strong> <%= comment.content %> <small><%= time_ago_in_words(comment.created_at) %> temu.</small>
	<% if current_user?(comment.user) %>
		<%= link_to "&times;".html_safe, comment, :confirm => "Fo' sho?", :method => :delete, :class => "close", :remote => true %>
	<% end %>
</li>

app/views/comments/_form.html.erb
<%= form_for(@comment, :remote => true, :html => {:class => "form-horizontal pull-left"}) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= image_tag(avatar_url_for(current_user), :class => "avatar") %>

    <%= f.hidden_field :movie_id, :value => movie.id %>
    <%= f.text_field :content, :placeholder => "Komentarz..." %>
 
    <%= f.submit "OK", :class => "enter btn", :disable_with => "Sec..." %>
<% end %>

app/views/comments/create.js.erb
<% if @comment.content != "" %>
	$("#moviesList #clip_<%=@comment.movie_id%> .comments").append("<%= escape_javascript( render :partial => 'comments/comment', :locals => { :comment => @comment} ) %>")       
	$("#lightbox_comments ul").append("<%= escape_javascript( render :partial => 'comments/comment', :locals => { :comment => @comment} ) %>")          
   
	$("#moviesList #clip_<%=@comment.movie_id%> #new_comment #comment_content").val("");                   
	$("#lightbox_comments #comment_content").val("");     

	$('#lightbox_comments ul').animate({ scrollTop: $("#comment_<%=@comment.id%>").offset().top }, 0);                   
      
	$('#moviesList').masonry({
	 	itemSelector: '.movie'
	});
<% end %>

app/views/comments/destroy.js.erb
$("#moviesList #clip_<%=@comment.movie_id%> #comment_<%=@comment.id%>").fadeOut(350, function() { $(this).remove(); });
$("#lightbox_comments #comment_<%=@comment.id%>").fadeOut(350, function() { $(this).remove(); });
$("#moviesList").masonry( 'reload' );

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Movie</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user_id %></td>
    <td><%= comment.movie_id %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Movie:</b>
  <%= @comment.movie_id %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>