config/routes.rb
Tuduk::Application.routes.draw do

  resources :invitations, only: [:index, :new]
  resources :authentications
  resources :comments
  resources :likes
  resources :movies, only: [:show, :index, :new]
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy, :index]
  resources :activities, only: [:index]

  root :to => 'pages#home'

  match "/signup", to: 'users#new'
  match "/signin", to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match "/about", to: 'pages#about'
  match "/submit", to: 'pages#submit'
  match "/bookmarklet", to: 'pages#bookmarklet'
  match "/library", to: 'pages#library'

  match '/auth/:provider/callback' => 'authentications#create'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
 
  before_filter :signed_in_user, except: [:show]
  before_filter :correct_user, only: [:destroy]
  before_filter :authenticate, only: [:new, :index]

  layout "clean", only: [:show]


  def index    
    @movies = Movie.order('id ASC')
    respond_to do |format|
      format.xml
      format.json { render json: @movies }
    end  
  end

  def show
    @movie = Movie.find(params[:id])
    @comment = Comment.new
    @movie.views_update    
    respond_to do |format|
      format.html 
      format.js
    end
  end

  def new
    require "open-uri"
    movies = ActiveSupport::JSON.decode(open("http://www.najsu.pl/movies.json"))
    movies.each do |movie|
      mv = Movie.new
      mv.resource_id = movie["resource_id"]
      mv.user_id     = 1
      mv.title       = movie["title"]
      mv.source      = movie["source"]
      mv.thumbnail   = movie["thumbnail"]
      mv.save
    end
    redirect_to root_path, notice: 'Zaimportowano filmy.'     
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to root_path, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.js
    end
  end



  protected

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == "najsu" && password == "2l3uh*&!@^)!(@#4uo23i4&!@^%#"
      end
    end

  private

    def correct_user
      movie = Movie.find(params[:id])
      user = movie.user
      redirect_to(root_path) unless current_user?(user)
    end


end

app/helpers/movies_helper.rb
module MoviesHelper

	def users_liked(movie)
		movie.likes.all.map{|like|like.user.name}.join(", ")
	end

	def thumbnail_url(video_id, source)
		if source.to_i == 1
			return "http://img.youtube.com/vi/#{video_id}/hqdefault.jpg"
		elsif source.to_i == 2
			return vimeo_thumbnail_url(video_id)			
		else
			return "http://img.youtube.com/vi/0/hqdefault.jpg"
		end
	end

	def vimeo_thumbnail_url(vimeo_id)
		require "open-uri"
		video_json = ActiveSupport::JSON.decode(open("http://vimeo.com/api/v2/video/#{vimeo_id}.json"))
		return video_json[0]["thumbnail_large"]
	end


end

app/views/movies/_form.html.erb
<%= form_for(@movie, :html => { :class => "well form-inline"}) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :resource_id, :placeholder => "Youtube movie ID" %>
    <%= f.submit :class => "btn btn-primary" %>
    
<% end %>

app/views/movies/_lightbox.html.erb
<ul class="actions unstyled" id="movieActions">
	<% if defined? page %>
		<%= render :partial => "movies/lightboxActions", :locals => { :movie => movie, :page => page } %>
	<% else %>
		<%= render :partial => "movies/lightboxActions", :locals => { :movie => movie } %>
	<% end %>
</ul>

<div id="lightbox_comments">
	<ul>
		<%= render movie.comments %>
	</ul>
		<% if signed_in? %>	<%= render :partial => "comments/form", :locals => { :movie => movie } %> <% end %>
</div>

<div class="lightbox">
	<div class="content" id="lightbox_content">

		<% if movie.source == 1 %>
			<embed src="http://www.youtube.com/v/<%=movie.resource_id%>&autoplay=1&rel=0&autohide=1&cc_load_policy=0&controls=1&hd=1&egm=0" type="application/x-shockwave-flash" wmode="transparent" id="embed_video">
			</embed>
		<% elsif movie.source == 2 %>
			<iframe src="http://player.vimeo.com/video/<%=movie.resource_id%>?autoplay=1" width="853" height="480" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
		<% else %>
			SHIT
		<% end %>
	</div>
</div>

app/views/movies/_lightboxActions.html.erb
<% if defined? page %>
	<li><a id="bye" class="single_page" href="/">Close</a></li>	
<% else %>
	<li><a id="bye">Close</a></li>	
<% end %>


<% if signed_in? %>

	<% cssClass = "active" if movie.liked?(current_user.id) %>
	<%= form_for(movie.likes.build, :remote => true) do |f| %>
		<%= f.hidden_field :movie_id, :value => movie.id %>
	  <li><%= f.submit "Like", :id => "like", :class => cssClass, :rel => "popover", "data-content" => users_liked(movie), 
	  "data-original-title" => "Lubią to (#{movie.likes_count})" %></li>
	<% end %>

	<li><a id="comments">Comments</a></li>

<% else %>

	<li><%= link_to "Nice", signin_path, :id => "like" %></li>

<% end %>

	<li class="avatar">
		<div class="avatar">
			<div class="mask"></div>
			<%= link_to(image_tag(avatar_url_for(movie.user), :size => "32x32"), user_path(movie.user), :rel => "tooltipLeft", :title => "#{movie.user.name}") %>
		</div>	
	</li>

app/views/movies/_movie.html.erb
<div class="movie<%= ' vimeo' if movie.source == 2 %>" id="clip_<%=movie.id%>">
	<%= link_to(movie_path(movie.id), :remote => true) do %>
		<div class="play"></div>
		<%= image_tag(movie.thumbnail) %>
	<% end %>
	<ul class="comments">
		<li class="author">

			<div class="title">
				<%= "<p>#{truncate(movie.title, :length => 60)}</p>".html_safe if movie.title %>
				<div class="counters">
					<div class="views_count" rel="tooltip" title="Obejrzeń"><%= movie.views_count %></div> 
					<div class="likes_count" rel="tooltip" title="Polubień"><%= movie.likes_count %></div>
					<div class="comments_count" rel="tooltip" title="Komentarzy"><%= movie.comments_count %></div>
					<div class="reposts_count" rel="tooltip" title="Repostów"><%= movie.reposts_count %></div>
				</div>
			</div>

			<div class="data">
				<div class="content">
					<% if movie.reposts_count > 1 %>
						<% movie.reposts.take(5).each do |repost| %>
							<%= link_to(image_tag(avatar_url_for(repost.user), :class => "avatar", :title => repost.user.name, 
							:rel => "tooltip"), user_path(repost.user), :class => "avatar") %>
						<% end %>					
					<% else %>
						<%= link_to(image_tag(avatar_url_for(movie.user), :class => "avatar"), user_path(movie.user), :class => "avatar") %>
						<strong><%= movie.user.name %></strong><br/>
						<small><%= time_ago_in_words(movie.created_at) %> temu.</small>
					<% end %>
				</div>
				<div class="action">
					<% if signed_in? && current_user?(movie.user) && 1 == 2 %>	
						<%= link_to "&times;".html_safe, movie, :confirm => "Entire movie fo' sho?", :method => :delete, :class => "btn btn-mini pull-right", :remote => true %>
					<% end %>
				</div>
			</div>
			
		</li>
		<% if movie.comments_count > 5 %>
			<% movies_left = movie.comments_count - 5 %>
			<li class="more"><%= link_to("Pokaż jeszcze #{movies_left} komentarzy", movie_path(movie.id), :remote => true) %></li>
		<% end %>
		<%= render movie.comments.last(5) %>
	</ul>
	<% if signed_in? %>	<%= render :partial => "comments/form", :locals => { :movie => movie } %> <% end %>
</div>

app/views/movies/_repost.html.erb
<% if repost.movie %>

	<div class="movie<%= ' vimeo' if repost.movie.source == 2 %>" id="clip_<%=repost.movie.id%>">
		<%= link_to(movie_path(repost.movie.id), :remote => true) do %>
		<div class="play"></div>
		<%= image_tag(repost.movie.thumbnail) %>
		<% end %>

		<ul class="comments">
			<li class="author">
				<div class="title">
				<%= "<p>#{truncate(repost.movie.title, :length => 34)}</p>".html_safe if repost.movie.title %>
				<div class="counters">
				<div class="views_count" rel="tooltip" title="Obejrzeń"><%= repost.movie.views_count %></div> 
				<div class="likes_count" rel="tooltip" title="Lajków"><%= repost.movie.likes_count %></div>
				<div class="comments_count" rel="tooltip" title="Komentarzy"><%= repost.movie.comments_count %></div>
				<div class="reposts_count" rel="tooltip" title="Repostów"><%= repost.movie.reposts_count %></div>
				</div>
				</div>
			</li>
		</ul>
	</div>

<% end %>

app/views/movies/destroy.js.erb
$("#moviesList #clip_<%=@movie.id%>").fadeOut(350, function() { $(this).remove(); });
$("#moviesList").masonry( 'reload' );

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<%= link_to "All stuff", movies_path %> | 
<%= link_to "Last week popular", movies_path(:popular => "fuckyea") %>

<h1>Listing movies</h1>

<table>
  <tr>
    <th>Resource</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td>
      <%= image_tag("http://img.youtube.com/vi/#{movie.resource_id}/hqdefault.jpg", :size => "50x50") %>
      <%= movie.resource_id %>
    </td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %><hr/>

<% if params[:popular] %>
  <%= will_paginate @movies, :page_links => false, :next_label => 'Load more!' %>
<% end %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<% content_for :title do %>
	<%= @movie.title %>
<% end %>

<% content_for :head do %>
	<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
<% end %>

<div class="overlay" id="cinema">
	<%= render :partial => 'movies/lightbox', :locals => { :movie => @movie, :page => "static" } %>
</div>

<script type="text/javascript">
	$(window).load(function(ev){	
		$('.overlay').css('display','table');	
		lightboxButtons();
		resizeWindow();
	})
</script>

app/views/movies/show.js.erb
$('.overlay').css('display','table');
$('#cinema').html("<%= escape_javascript( render :partial => 'movies/lightbox', :locals => { :movie => @movie} ) %>");
location.hash='movie=<%="#{@movie.id}"%>';
lightboxButtons();
resizeWindow();