config/routes.rb
Tuduk::Application.routes.draw do

  resources :invitations, only: [:index, :new]
  resources :authentications
  resources :comments
  resources :likes
  resources :movies, only: [:show, :index, :new]
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy, :index]
  resources :activities, only: [:index]

  root :to => 'pages#home'

  match "/signup", to: 'users#new'
  match "/signin", to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match "/about", to: 'pages#about'
  match "/submit", to: 'pages#submit'
  match "/bookmarklet", to: 'pages#bookmarklet'
  match "/library", to: 'pages#library'

  match '/auth/:provider/callback' => 'authentications#create'

end

app/views/pages/_homeNotice.html.erb
<% if @movies.count < 1 && signed_in? %>
	<p class="page_info"><a href="users">Dodaj lub zaproś znajomych,</a> by obserwować co oglądają!</p>
<% end %>

app/views/pages/about.html.erb
<% provide(:title, "O Najsu") %>

<div class="container">
	<div id="about" class="row">

		<div class="span6">
			Najsu jest Twoim agregatorem i źródłem najlepszych filmików w sieci oraz wśród Twoich znajomych.
			Wskazówki, krytykę i słowa otuchy słać na <a href="mailto:matbur@me.com">matbur@me.com</a>
		</div>

	</div>
</div>

app/views/pages/bookmarklet.html.erb
<% provide(:title, "dodaj zakładkę") %>

<div id="bookmarklet_page">

	<div class="intro">
		Udostępniaj jednym kliknięciem filmy, które oglądasz!
	</div>
	
	<div class="scriptlet">
		<a href="javascript:(function(){document.body.appendChild(document.createElement('script')).src='http://www.najsu.pl/bookmarklet.js';})();" class="bookmarklet">Najsu!</a>		
		<div class="arrow"></div>
		<div class="browser"></div>
	</div>

	<div class="content">
		<div class="header">
			Zakładka zamontowana? Przejdźmy do dzieła!
		</div>
		<div class="main">
			<div class="hint"></div>
			<div class="browsers"></div>
			<ul class="steps unstyled">
				<li>
					<p>Oglądasz spoko filmik na YouTube czy Vimeo</p>
				</li>
				<li>
					<p>Klikasz w zakładkę "Najsu!"</p>
				</li>
				<li>
					<p>Filmik zostaje dodany do Twojej kolekcji oraz udostępniony światu i znajomym</p>
				</li>
			</ul>
			<a href="/movies/146" id="tutorial_button">
				Zobacz filmik instruktażowy!
			</a>
		</div>
		<div class="notice">
			<p>Zakładka póki co działa na stronach YouTube i Vimeo, <strong>więcej wkrótce!</strong></p>
		</div>
	</div>
	
</div>

app/views/pages/home.html.erb
<% provide(:title, "najlepsze filmiki z sieci!") %>

<div class="row-fluid<%=featuredCss%>" id="featured">

	<div class="span12">

			<div class="unWrap">			
				<p id="discoverMovies">Odkrywaj, najlepsze filmy na Świecie i w Twoim otoczeniu!</p>
	  		<% unless current_user %>
	  			<%= link_to "Zaloguj z Facebook", "auth/facebook", :class => "button-facebook facebook_popup" %>
	  			<p id="or">lub</p>
	  			<%= link_to "Załóż konto", signup_path, :class => "button-signup" %>
	  		<% end %>
	  	</div>

			<!--
			<a class="close pull-right">&times;</a>
			-->

  		<% if signed_in? %>
				<% if current_user.facebook? %>
					<%= link_to "Zaproś znajomych z Facebook!", invitations_path, :remote => true, :disable_with => "Ładowanie...", :class => "button button-facebook" %>
				<% end %>
	  		<%= link_to "Subskrybuj ludzi!", relationships_path, :remote => true, :class => "button button-orange" %> 
			<% end %>		

	</div>
</div>

<% if signed_in? %>
<div id="categories" class="row-fluid">

	<ul class="switcher unstyled">
		<li id="switcherItem0"><%= link_to "Najnowsze", root_path(:feed => "newest"), :id => "newest", :rel => "tooltip", :title => "Ostatnio dodane", :remote => true %></li>
		<li id="switcherItem1"><%= link_to "Popularne", root_path(:feed => "popular"), :id => "popular", :rel => "tooltip", :title => "Popularne", :remote => true %></li>
		<li id="switcherItem2"><%= link_to "Od znajomych", root_path(:feed => "friends"), :id => "friends", :rel => "tooltip", :class => "active", :title => "Od znajomych", :remote => true %></li>
		<li id="switcherItem3"><%= link_to "Dyskutowane", root_path(:feed => "discussed"), :id => "discussed", :rel => "tooltip", :title => "Dyskutowane", :remote => true %></li>
		<li id="switcherItem4"><%= link_to "Oglądane", root_path(:feed => "watched"), :id => "watched", :rel => "tooltip", :title => "Oglądane", :remote => true %></li>
	</ul>

</div>
<% end %>


<div class="row-fluid">
		<div id="information">
			<%= render :partial => 'pages/homeNotice' %>
		</div>
		<div id="moviesList" class="big">
			<%= render @movies %>
		</div>
		<div id="paginaDomina">
			<%= will_paginate @movies, :page_links => false, :next_label => 'Więcej!' %>
		</div>	
		<%= javascript_tag " $('.pagination a').attr('data-remote', 'true'); $('.previous_page').remove()" %>
</div>					

app/views/pages/home.js.erb
<% if params[:page] %>
	<% if params[:page].to_i <= @movies.total_pages %>
		$("#moviesList").append("<%= escape_javascript( render @movies ) %>");       
		$("#moviesList").masonry( 'reload' );       
		$("#paginaDomina").html("<%= escape_javascript( will_paginate @movies, :page_links => false, :next_label => 'Więcej!' ) %>");       
	  $('.pagination a').attr('data-remote', 'true');
	  $('.previous_page').remove()
	  $('[rel="tooltip"]').tooltip();
	<% end %>
<% else %>
	$("#moviesList").html("<%= escape_javascript( render @movies ) %>");       
	$("#information").html("<%= escape_javascript( render :partial => 'pages/homeNotice' ) %>");       
	$("#paginaDomina").html("<%= escape_javascript( will_paginate @movies, :page_links => false, :next_label => 'Więcej!' ) %>");       
	$("#moviesList").masonry( 'reload' );       
	$('[rel="tooltip"]').tooltip();
	$('.pagination a').attr('data-remote', 'true');
	$('.previous_page').remove()
	heightCheck();
<% end %>


/*
$("#moviesList").delay(2000)
    .queue(function(n) {
        $(this).html("<%= escape_javascript( render @movies ) %>");       
        n();
        $("#moviesList").masonry( 'reload' );
    })
*/

app/views/pages/library.html.erb
<div id="categories" class="row-fluid library">
	<div class="avatar" id="slidabilty">
		<div class="mask"></div>
		<%= image_tag(avatar_url_for(current_user),:size => '82x82') %>
	</div>
</div>

<div class="row-fluid libary-navi">
	<div class="btn-group">
		<%= link_to "Twoje filmy", library_path(:show => "yours"), :id => "yours", :class => "btn active", :remote => true %>
		<%= link_to "Lubiane", library_path(:show => "liked"), :id => "liked", :class => "btn", :remote => true %>
		<%= link_to "Dyskutowane", library_path(:show => "commented"), :id => "commented", :class => "btn", :remote => true %>
	</div>
</div>


<div class="row-fluid">

	<div id="moviesList" class="library">
		<%= render :partial => "movies/repost", :collection => @reposts %>
	</div>
</div>

app/views/pages/library.js.erb
$("#moviesList").html("<%= escape_javascript( render :partial => 'movies/repost', :collection => @reposts ) %>");       
$("#moviesList").masonry( 'reload' );       

app/views/pages/submit.html.erb
<% if signed_in? %>
	
	<% if params[:resource_id] %>
		<p style="padding: 0 0 0 30px">Ładowanie...</p>
	<% end %>

	<% if params[:notice] %>
		<p style="padding: 0 0 0 30px"><%= params[:notice] %></p>
		<script type="text/javascript">
			setTimeout("window.close()", 1000);	
		</script>
	<% end %>

<% else %>

	Nie jesteś zalogowany.<br/>
	<%= link_to "Zaloguj się tutaj!", signin_path, :target => "_blank", :id => "close" %>
	<script type="text/javascript">
		$('#close').click(function() {
			setTimeout("window.close()", 100);	
		});
	</script>

<% end %>

app/views/pages/timeline.html.erb
<div class="row-fluid" id="timeline">

		<% @movies.each do |day, movies| %>
			<ul class="unstyled movies">
				<div class="first"><%= day.strftime("%m.%d") %></div>
				<% movies.each do |movie| %>
	    		<div class="movie" id="clip_<%=movie.id%>">
					<%= link_to(movie_path(movie.id), :remote => true) do %>
						<div class="play"></div>
						<%= image_tag("http://img.youtube.com/vi/#{movie.resource_id}/hqdefault.jpg") %>
					<% end %>
				</div>
	  		<% end %>
  		</ul>
  	<% end %>

</div>					