config/routes.rb
Tuduk::Application.routes.draw do

  resources :invitations, only: [:index, :new]
  resources :authentications
  resources :comments
  resources :likes
  resources :movies, only: [:show, :index, :new]
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy, :index]
  resources :activities, only: [:index]

  root :to => 'pages#home'

  match "/signup", to: 'users#new'
  match "/signin", to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match "/about", to: 'pages#about'
  match "/submit", to: 'pages#submit'
  match "/bookmarklet", to: 'pages#bookmarklet'
  match "/library", to: 'pages#library'

  match '/auth/:provider/callback' => 'authentications#create'

end

app/views/layouts/_footer.html.erb
<a href="/about">O Najsu</a>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top" id="header">
	 <div class="navbar-inner">

			<div class="container-fluid bezel">
			</div>

			<div class="container-fluid bar">
				<%= link_to "Najsu", root_path, :class => "brand" %>

				<% if signed_in? %>
					<div class="user">
						<div class="avatar">
							<div class="mask"></div>
							<%= image_tag(avatar_url_for(current_user), :size => "38x38") %>
						</div>
						<div class="name">
							<div class="arrow"></div>
							<%= link_to current_user.name, user_path(current_user), :class => "content" %>
						</div>
						<div id="notifications_counter">
							<%= render "layouts/headerCounter" %>							
						</div>
						<div id="activities_baloon">
							<div class="arrow"></div>							
							<ul class="unstyled" id="counter_activities">
							</ul>						
							<div class="actions">
								<a href="activities">Wszystkie aktywności</a>
								<a href="#feed" id="mobile_activities_close">Zamknij panel</a>
							</div>
						</div>
					</div>
				<% end %>

				
	      <ul class="nav">
						<% if signed_in? %>
							<li id="bookmarklet"><%= link_to "Strona z zakładką", bookmarklet_path, :class => active?("bookmarklet") %></li>
						<% end %>

	          <li><%= link_to "Główna", root_path, :class => active?("home") %></li>
						<li><%= link_to "Ludzie", users_path, :class => active?("users", "index") %></li>

						<% if signed_in? %>
		        	<li><%= link_to "Aktywności", activities_path, :class => active?("activities", "index") %></li>
		        <% end %>

	          <% unless signed_in? %>
	            <li><%= link_to "Zaloguj się", signin_path %></li>
	            <li><%= link_to "Rejestracja", signup_path %></li>
	          <% end %>

            <% if signed_in? %>
            	<li><%= link_to "Zbiory", library_path, :class => active?("library") %></li>
            	<li><%= link_to "Wyloguj się", signout_path, method: "delete", :class => "clean" %></li>
	          <% end %>
	      </ul>
	  	</div>


	</div>
</div>

app/views/layouts/_headerCounter.html.erb
<% counter = current_user.activities_counter %>						
<% counter_css = "active" if counter > 0 %>							
<%= link_to counter, activities_path, :class => counter_css, :remote => true, :disable_with => "Ładowanie..." %>

app/views/layouts/_modal.html.erb
<div class="modal hide fade in" id="actionsModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Header</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta content="filmiki, rozrywka, społeczność, agregator" name="keywords">
  <meta content="Najsu pozwala Ci odkrywać wszystkie najfajniejsze filmiki w sieci, popularne zarówno na świecie jak i wśród Twoich znajomych!" name="description">

  <link rel="shortcut icon" type="image/png" href="assets/favicon.ico" />

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1&appId=265664360191857";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30915752-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

	</script>
</head>
<body <%="class='app'" if signed_in? %>>

	<%= render "layouts/header" %>

	<!--  content -->
	<div class="container-fluid<%= ' movies'if action_name == 'home' %>" id="content">
		<div class="row-fluid">
			<div class="span12">
				<% flash.each do |key, value| %>
		      <div class="alert alert-<%= key %>"><%= value %></div>
		    <% end %>
				<%= yield %>
			</div>
		</div>
	</div>

	<!-- footer -->
	<div id="footer">
		<%= render "layouts/footer" %>
	</div>

 	<%= render "layouts/modal" %>

  <div class="overlay" id="cinema">
  	<%= yield :cinema %>
  </div>
  	
</body>
</html>

app/views/layouts/clean.html.erb
<!DOCTYPE html>
<html class="clean">
<head>
  <title><%= page_title(yield(:title)) %></title>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" type="image/png" href="assets/favicon.ico" />

  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30915752-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

	</script>
</head>
<body>

	
		<%= yield %>
		
	
</body>
</html>